---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"

- name: Init Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
