FROM ansible-base:latest

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /ansible

RUN apt-get update && apt-get install -y \
    ansible \
    openssh-client \
 && rm -rf /var/lib/apt/lists/*

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
 && unzip awscliv2.zip \
 && ./aws/install \
 && rm -rf awscliv2.zip aws/

CMD ["sleep", "infinity"]
