FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /ansible

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    openssh-client \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    ansible-core \
    awscli \
    awscli-local

RUN ansible-galaxy collection install community.aws

CMD ["sleep", "infinity"]
