FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /ansible

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    openssh-client \
    sshpass \
    gcc \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    ansible \
    boto3 \
    botocore \
    awscli \
    awscli-local

RUN ansible-galaxy collection install community.general community.aws

CMD ["sleep", "infinity"]
