galaxy_info:
  author: Felipe Gutiérrez
  description: Nginx Laboratory for Ansible
  company: "Personal"
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
