---
- name: Config IAM on Ministack
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "../group_vars/nodes.yml"

  vars:
    desired_groups: ["admin-group", "dev-group"]
    desired_users:
      - { name: "ana-admin", group: "admin-group" }
      - { name: "pedro-dev", group: "dev-group" }
      - { name: "marta-dev", group: "dev-group" }

  tasks:
    - name: Crear grupos en IAM
      ansible.builtin.command: >
        aws --endpoint-url={{ aws_endpoint_url }} iam create-group --group-name {{ item }}
      loop: "{{ desired_groups }}"
      register: group_output
      changed_when: "'EntityAlreadyExists' not in group_output.stderr and group_output.rc == 0"
      failed_when: "group_output.rc != 0 and 'EntityAlreadyExists' not in group_output.stderr"

    - name: Crear usuarios en IAM
      ansible.builtin.command: >
        aws --endpoint-url={{ aws_endpoint_url }} iam create-user --user-name {{ item.name }}
      loop: "{{ desired_users }}"
      register: user_output
      changed_when: "'EntityAlreadyExists' not in user_output.stderr and user_output.rc == 0"
      failed_when: "user_output.rc != 0 and 'EntityAlreadyExists' not in user_output.stderr"

    - name: Asignar usuarios a grupos
      ansible.builtin.command: >
        aws --endpoint-url={{ aws_endpoint_url }} iam add-user-to-group 
        --user-name {{ item.name }} --group-name {{ item.group }}
      loop: "{{ desired_users }}"
      register: assign_output
      changed_when: "'LimitExceeded' not in assign_output.stderr and assign_output.rc == 0"
      failed_when: "assign_output.rc != 0 and 'LimitExceeded' not in assign_output.stderr"
